# .streamlit/config.toml
# Configuración de Streamlit para NutriSenseIA
# Sistema de Anemia Infantil - Datatón 2025

[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showSidebarNavigation = false
showErrorDetails = true
toolbarMode = "minimal"

[ui]
hideTopBar = false
